//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiyat
    {
        public int Id { get; set; }
        public decimal Deger { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<int> OtelOlanaklariId { get; set; }
        public Nullable<int> OdaTipiId { get; set; }
        public Nullable<int> EkHizmetId { get; set; }
    
        public virtual EkHizmet EkHizmet { get; set; }
        public virtual OdaTipi OdaTipi { get; set; }
        public virtual OtelOlanaklari OtelOlanaklari { get; set; }
    }
}
