//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervasyon()
        {
            this.Rezervasyon_EkHizmet = new HashSet<Rezervasyon_EkHizmet>();
            this.Rezervasyon_Musteri = new HashSet<Rezervasyon_Musteri>();
            this.Rezervasyon_Oda = new HashSet<Rezervasyon_Oda>();
            this.Rezervasyon_OtelOlanaklari = new HashSet<Rezervasyon_OtelOlanaklari>();
        }
    
        public int Id { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public int MusteriId { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon_EkHizmet> Rezervasyon_EkHizmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon_Musteri> Rezervasyon_Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon_Oda> Rezervasyon_Oda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon_OtelOlanaklari> Rezervasyon_OtelOlanaklari { get; set; }
    }
}
