//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyon_OtelOlanaklari
    {
        public int Id { get; set; }
        public int RezervasyonId { get; set; }
        public int OtelOlanaklariId { get; set; }
        public int ToplamTutar { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        public virtual OtelOlanaklari OtelOlanaklari { get; set; }
        public virtual Rezervasyon Rezervasyon { get; set; }
    }
}
