//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oda()
        {
            this.Oda_EkHizmet = new HashSet<Oda_EkHizmet>();
            this.Rezervasyon_Oda = new HashSet<Rezervasyon_Oda>();
        }
    
        public int Id { get; set; }
        public byte Kapasite { get; set; }
        public int OtelId { get; set; }
        public int OdaTipiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oda_EkHizmet> Oda_EkHizmet { get; set; }
        public virtual OdaTipi OdaTipi { get; set; }
        public virtual Otel Otel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon_Oda> Rezervasyon_Oda { get; set; }
    }
}
