//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda_EkHizmet
    {
        public int Id { get; set; }
        public int OdaId { get; set; }
        public int EkHizmetId { get; set; }
    
        public virtual EkHizmet EkHizmet { get; set; }
        public virtual Oda Oda { get; set; }
    }
}
