//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string BodyText { get; set; }
        public Nullable<bool> IsNavbar { get; set; }
        public Nullable<bool> IsFooter { get; set; }
        public string ButtonUrl { get; set; }
        public string ButtonName { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    }
}
