//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
